name: Call sub test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: callsub
        uses: ./.github/workflows/sub.yml
        with:
          BUILD_NAME: ${{ github.ref_name }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.ref_name }}
      - name: show artifact
        run: |
          ls -l
          cat via_env.txt
          cat via_context.txt
