name: Call sub test
on: 
  push:
    branches:
      - main
jobs:
  callsub:
    uses: ./.github/workflows/sub.yml
    with:
      buildname: 'STATIC STRING' # ${{ github.ref_name }}
  build:
    needs: callsub
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.inputs.BUILD_NAME }}
      - name: show artifact
        run: |
          ls -l
          cat via_env.txt
          cat via_context.txt
