name: Call sub test
on:
  push:
    branches:
      - main
      - develop-*
  create:
jobs:
  callsub:
    if:
      contains( github.ref_name, 'develop-' ) ||
      contains( github.ref_name, 'main' )
    uses: ./.github/workflows/sub.yml
    with:
      BUILD_NAME: ${{ github.ref_name }}
  build:
    needs: callsub
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.ref_name }}
      - name: show artifact
        run: |
          ls -l
          cat via_env.txt
          cat via_context.txt
