name: Call sub test
on:
  push:
    branches:
      - main
      - develop-*
    tags:
      - 'v*-alpha*'
      - 'v*-beta*'
      - 'v*-rc*'
  create:
jobs:
  callsub:
    if: |
      ((github.event_name == 'create') &&
        contains( github.ref_name, 'develop-' )) ||
      (github.event_name == 'push')
    uses: ./.github/workflows/sub.yml
    with:
      BUILD_NAME: ${{ github.ref_name }}
  build:
    needs: callsub
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.ref_name }}
      - name: show artifact
        run: |
          ls -l
          cat via_env.txt
          cat via_context.txt
