name: Call sub test
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: input shaka tag
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
    steps:
      - name: Call sub
        uses: ./.github/workflows/sub.yml
        with:
          tag: ${{ github.event.inputs.tag }}