name: Distribute
on: 
  push:
    branches:
      - develop-*
  pull_request:
    types:
      - labeled
jobs:
  call-build-workflow:
    if: |
      ((github.event_name == 'pull_request') &&
        (github.event.label.name == 'preview on devsite')) ||
      (github.event_name == 'push')
    uses: ./.github/workflows/sub.yml
    with:
      BUILD_NAME: ${{ github.ref_name }}
  publish:
    runs-on: ubuntu-latest
    needs: call-build-workflow
    steps:
      - name: Run workflow
        run: |
          echo 'run workflow ${{ github.ref_name }}'
