name: Sub workflow
on: 
  workflow_call:
    inputs:
      BUILD_NAME:
        type: string
        required: true
        default: 'build'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
      ENV_BUILD_NAME: ${{ inputs.BUILD_NAME }}
    steps:
      - name: echo via env
        run: |
          echo ${{ inputs.BUILD_NAME }} > via_env.txt
          echo $ENV_BUILD_NAME
      - name: echo context
        run: |
          echo ${{ inputs.BUILD_NAME }} > via_context.txt
          echo ${{ inputs.BUILD_NAME }}
      - name: escape build name
        id: escape_build_name
        run: |
          echo "value=$(echo '${{ inputs.BUILD_NAME }}' | sed 's/\//-/g')" >> $GITHUB_OUTPUT
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.escape_build_name.outputs.value }}
          path: |
            .