name: Sub workflow
on: 
  workflow_call:
    inputs:
      tag:
        description: input shaka tag
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
      TAG: ${{ github.event.inputs.tag }}
    steps:
      - name: echo via env
        run: |
          echo ${{ github.event.inputs.tag }} > via_env.txt
          echo $TAG
      - name: echo tag
        run: |
          echo ${{ github.event.inputs.tag }} > via_context.txt
          echo ${{ github.event.inputs.tag }}
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.tag }}
          path: |
            .
