name: Sub workflow
on: 
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Tokyo'
      ENV_BUILD_NAME: ${{ github.event.inputs.tag }}
    steps:
      - name: echo via env
        run: |
          echo ${{ github.event.inputs.tag }} > via_env.txt
          echo $ENV_BUILD_NAME
      - name: echo context
        run: |
          echo ${{ github.event.inputs.tag }} > via_context.txt
          echo ${{ github.event.inputs.tag }}
      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.tag }}
          path: |
            .
